trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

jobs:
    - job: Production
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      steps:
          - task: Npm@1
            name: Install_Dependencies
            inputs:
                command: 'install'
          - task: Npm@1
            name: Build
            inputs:
                command: 'custom'
                customCommand: 'run build'
          - publish: $(System.DefaultWorkingDirectory)/build
            artifact: build
